<?php

/**
 * DBAL SQL state codes.
 *
 * Origin.
 *
 * @author Luke Carrier <luke@carrier.im>
 * @copyright 2014 Luke Carrier
 * @license Proprietary; all rights reserved
 */

namespace Origin\Database\Dbal;

/**
 * SQLSTATE codes.
 *
 * The SQLSTATE codes, as outlined in ANSI SQL-92, describe the various
 * execution states of SQL queries.
 *
 * This library is provided to complement the PDO-like driver interface.
 */
class SqlStateCodes {
    const AMBIGUOUS_CURSOR_NAME_NO_SUBCLASS = '3C000';
    const CARDINALITY_VIOLATION_NO_SUBCLASS = '21000';
    const CONNECTION_EXCEPTION_NO_SUBCLASS = '08000';
    const CONNECTION_EXCEPTION_CONNECTION_DOES_NOT_EXIST = '08003';
    const CONNECTION_EXCEPTION_CONNECTION_FAILURE = '08006';
    const CONNECTION_EXCEPTION_CONNECTION_NAME_IN_USE = '08002';
    const CONNECTION_EXCEPTION_SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION = '08001';
    const CONNECTION_EXCEPTION_SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION = '08004';
    const CONNECTION_EXCEPTION_TRANSACTION_RESOLUTION_UNKNOWN = '08007';

    const DATA_EXCEPTION_NO_SUBCLASS = '22000';
    const DATA_EXCEPTION_CHARACTER_NOT_IN_REPERTOIRE = '22021';
    const DATA_EXCEPTION_DATETIME_FIELD_OVERFLOW = '22008';
    const DATA_EXCEPTION_DIVISION_BY_ZERO = '22012';
    const DATA_EXCEPTION_ERROR_IN_ASSIGNMENT = '22005';
    const DATA_EXCEPTION_INDICATOR_OVERFLOW = '22022';
    const DATA_EXCEPTION_INTERVAL_FIELD_OVERFLOW = '22015';
    const DATA_EXCEPTION_INVALID_CHARACTER_VALUE_FOR_CAST = '22018';
    const DATA_EXCEPTION_INVALID_DATETIME_FORMAT = '22007';
    const DATA_EXCEPTION_INVALID_ESCAPE_CHARACTER = '22019';
    const DATA_EXCEPTION_INVALID_ESCAPE_SEQUENCE = '22025';
    const DATA_EXCEPTION_INVALID_PARAMETER_VALUE = '22023';
    const DATA_EXCEPTION_INVALID_TIME_ZONE_DISPLACEMENT = '22009';
    const DATA_EXCEPTION_NULL_VALUE_NO_INDICATOR_PARAMETER = '22002';
    const DATA_EXCEPTION_NUMERIC_VALUE_OUT_OF_RANGE = '22003';
    const DATA_EXCEPTION_STRING_DATA_LENGTH_MISMATCH = '22026';
    const DATA_EXCEPTION_STRING_DATA_RIGHT_TRUNCATION = '22001';
    const DATA_EXCEPTION_SUBSTRING_ERROR = '22011';
    const DATA_EXCEPTION_TRIM_ERROR = '22027';
    const DATA_EXCEPTION_UNTERMINATED_C_STRING = '22024';

    const DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST_NO_SUBCLASS = '2B000';

    const DYNAMIC_SQL_ERROR_NO_SUBCLASS = '07000';
    const DYNAMIC_SQL_ERROR_CURSOR_SPECIFICATION_CANNOT_BE_EXECUTED = '07003';
    const DYNAMIC_SQL_ERROR_INVALID_DESCRIPTOR_COUNT = '07008';
    const DYNAMIC_SQL_ERROR_INVALID_DESCRIPTOR_INDEX = '07009';
    const DYNAMIC_SQL_ERROR_PREPARED_STATEMENT_NOT_A_CURSOR_SPECIFICATION = '07005';
    const DYNAMIC_SQL_ERROR_RESTRICTED_DATA_TYPE_ATTRIBUTE_VIOLATION = '07006';
    const DYNAMIC_SQL_ERROR_USING_CLAUSE_DOES_NOT_MATCH_DYNAMIC_PARAMETER_SPEC = '07001';
    const DYNAMIC_SQL_ERROR_USING_CLAUSE_DOES_NOT_MATCH_TARGET_SPEC = '07002';
    const DYNAMIC_SQL_ERROR_USING_CLAUSE_REQUIRED_FOR_DYNAMIC_PARAMETERS = '07004';
    const DYNAMIC_SQL_ERROR_USING_CLAUSE_REQUIRED_FOR_RESULT_FIELDS = '07007';

    const FEATURE_NOT_SUPPORTED_NO_SUBCLASS = '0A000';
    const FEATURE_NOT_SUPPORTED_MULTIPLE_ENVIRONMENT_TRANSACTIONS = '0A001';

    const INTEGRITY_CONSTRAINT_VIOLATION_NO_SUBCLASS = '23000';

    const INVALID_AUTHORIZATION_SPECIFICATION_NO_SUBCLASS = '28000';
    const INVALID_CATALOG_NAME_NO_SUBCLASS = '3D000';
    const INVALID_CHARACTER_SET_NAME_NO_SUBCLASS = '2C000';
    const INVALID_CONDITION_NUMBER_NO_SUBCLASS = '35000';
    const INVALID_CONNECTION_NAME_NO_SUBCLASS = '2E000';
    const INVALID_CURSOR_NAME_NO_SUBCLASS = '34000';
    const INVALID_CURSOR_STATE_NO_SUBCLASS = '24000';
    const INVALID_SCHEMA_NAME_NO_SUBCLASS = '3F000';
    const INVALID_SQL_DESCRIPTOR_NAME_NO_SUBCLASS = '33000';
    const INVALID_SQL_STATEMENT_NAME_NO_SUBCLASS = '26000';
    const INVALID_TRANSACTION_STATE_NO_SUBCLASS = '25000';
    const INVALID_TRANSACTION_TERMINATION_NO_SUBCLASS = '2D000';

    const NO_DATA_NO_SUBCLASS = '02000';

    const REMOTE_DATABASE_ACCESS_NO_SUBCLASS = 'HZ000';

    const SUCCESSFUL_COMPLETION_NO_SUBCLASS = '00000';

    const SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION_NO_SUBCLASS = '42000';
    const SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION_IN_DIRECT_STATEMENT_NO_SUBCLASS = '2A000';
    const SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION_IN_DYNAMIC_STATEMENT_NO_SUBCLASS = '37000';

    const TRANSACTION_ROLLBACK_NO_SUBCLASS = '40000';
    const TRANSACTION_ROLLBACK_INTEGRITY_CONSTRAINT_VIOLATION = '40002';
    const TRANSACTION_ROLLBACK_SERIALIZATION_FAILURE = '40001';
    const TRANSACTION_ROLLBACK_STATEMENT_COMPLETION_UNKNOWN = '40003';
    const TRIGGERED_DATA_CHANGE_VIOLATION_NO_SUBCLASS = '27000';

    const WARNING_NO_SUBCLASS = '01000';
    const WARNING_CURSOR_OPERATION_CONFLICT = '01001';
    const WARNING_DISCONNECT_ERROR = '01002';
    const WARNING_IMPLICIT_ZERO_BIT_PADDING = '01008';
    const WARNING_INSUFFICIENT_ITEM_DESCRIPTOR_AREAS = '01005';
    const WARNING_NULL_VALUE_ELIMINATED_IN_SET_FUNCTION = '01003';
    const WARNING_PRIVILEGE_NOT_GRANTED = '01007';
    const WARNING_PRIVILEGE_NOT_REVOKED = '01006';
    const WARNING_QUERY_EXPRESSION_TOO_LONG_FOR_INFORMATION_SCHEMA = '0100A';
    const WARNING_SEARCH_CONDITION_TOO_LONG_FOR_INFORMATION_SCHEMA = '01009';
    const WARNING_STRING_DATA_RIGHT_TRUNCATION_WARNING = '01004';

    const WITH_CHECK_OPTION_VIOLATION_NO_SUBCLASS = '44000';
}
